Feature part 4
JoeyAlanS/Integration-project-backend pull request #3
Opened 2024-05-14 04:33 UTC by JoeyAlanS

2024-05-15 13:35 UTC, Bacuriim requested changes
Encontrei alguns poucos pontos no code review, por favor corrigi-los!

2024-05-15 13:35 UTC, Bacuriim commented on src/main/java/com/eletra/controllers/CategoryController.java
> +    }
Acredito que o "Return category" nesse método seria um "New category" ou "Add category", pois o método postCategoryEntity adiciona uma nova categoria na lista.

2024-05-15 13:35 UTC, Bacuriim commented on src/main/java/com/eletra/controllers/LineupController.java
> +    }
Mesmo ponto da categoryController, esse "Return line" deve ser alguma coisa que referencie uma adição, pois o método post adiciona um novo membro a lista.

2024-05-15 13:35 UTC, Bacuriim commented on src/main/java/com/eletra/controllers/ModelController.java
> +    }
Mesmo ponto da categoryController, esse "Return model" deve ser alguma coisa que referencie uma adição, pois o método post adiciona um novo membro a lista.

2024-05-16 13:07 UTC, Bacuriim approved these changes
Não foram encontradas novas pendências!

2024-05-17 15:49 UTC, XxTaro requested changes
Foi realizado o code review e foram encontrados pontos de melhoria

2024-05-17 15:49 UTC, gustavo-lopes-dev commented on src/main/java/com/eletra/Testando.java
Por qual motivo a classe Main que inicializa a Sprint tem o nome "Testando"?

2024-05-17 15:49 UTC, XxTaro commented on src/main/java/com/eletra/controllers/CategoryController.java
> +    }
Favor, não retornar uma String no método de update, e sim o proprio objeto salvo no banco, assim como é feito no método "postCategoryEntity"

2024-05-17 15:49 UTC, XxTaro commented on src/main/java/com/eletra/controllers/CategoryController.java
> +    }
Favor, melhorar retorno desse método, no caso ou retornar um valor booleano para retornar se realmente foi possível deletar esse item (porém, o método "delete" do JPA não retorna nada, logo seria interessante uma verificação se aquele item ainda continua no banco) ou então ser um método void

2024-05-17 15:49 UTC, XxTaro commented on src/main/java/com/eletra/controllers/LineupController.java
> +    }
Favor, melhorar retorno desse método, no caso ou retornar um valor booleano para retornar se realmente foi possível deletar esse item (porém, o método "delete" do JPA não retorna nada, logo seria interessante uma verificação se aquele item ainda continua no banco) ou então ser um método void

2024-05-17 15:49 UTC, XxTaro commented on src/main/java/com/eletra/controllers/LineupController.java
> +    }
Favor, não retornar uma String no método de update, e sim o proprio objeto salvo no banco, assim como é feito no método "postLineEntity"

2024-05-17 15:49 UTC, XxTaro commented on src/main/java/com/eletra/controllers/ModelController.java
> +    }
Favor, não retornar uma String no método de update, e sim o proprio objeto salvo no banco, assim como é feito no método "postModelEntity"

2024-05-17 15:49 UTC, XxTaro commented on src/main/java/com/eletra/controllers/ModelController.java
> +    }
Favor, melhorar retorno desse método, no caso ou retornar um valor booleano para retornar se realmente foi possível deletar esse item (porém, o método "delete" do JPA não retorna nada, logo seria interessante uma verificação se aquele item ainda continua no banco) ou então ser um método void

2024-05-17 21:54 UTC, JoeyAlanS commented on src/main/java/com/eletra/Testando.java
Havia esquecido de trocar o nome, por conta do tutorial.

2024-05-23 18:09 UTC, XxTaro approved these changes
Não foram encontradas novas pendências

2024-05-23 21:35 UTC, closed without merging